// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWiPWDD-Y4jx0o7egq20_LaojIldasIB4',
    appId: '1:908785933672:web:9595268fb36ec1d83d8add',
    messagingSenderId: '908785933672',
    projectId: 'rewardshub-9ba8b',
    authDomain: 'rewardshub-9ba8b.firebaseapp.com',
    storageBucket: 'rewardshub-9ba8b.firebasestorage.app',
    measurementId: 'G-LVHH9R8Y8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6txlZJsqsAjZ3RGM7j1rdOsk5K7O0IH0',
    appId: '1:908785933672:android:acbdaa27630c25d83d8add',
    messagingSenderId: '908785933672',
    projectId: 'rewardshub-9ba8b',
    storageBucket: 'rewardshub-9ba8b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCA7eAvs267K91ovHYvXErIGkEe8elOffM',
    appId: '1:908785933672:ios:3af4f16a18f44b7e3d8add',
    messagingSenderId: '908785933672',
    projectId: 'rewardshub-9ba8b',
    storageBucket: 'rewardshub-9ba8b.firebasestorage.app',
    iosClientId: '908785933672-3ks547841cn6lm8rc0boe3l4nmtb6kua.apps.googleusercontent.com',
    iosBundleId: 'com.rewardshub.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCA7eAvs267K91ovHYvXErIGkEe8elOffM',
    appId: '1:908785933672:ios:3af4f16a18f44b7e3d8add',
    messagingSenderId: '908785933672',
    projectId: 'rewardshub-9ba8b',
    storageBucket: 'rewardshub-9ba8b.firebasestorage.app',
    iosClientId: '908785933672-3ks547841cn6lm8rc0boe3l4nmtb6kua.apps.googleusercontent.com',
    iosBundleId: 'com.rewardshub.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWiPWDD-Y4jx0o7egq20_LaojIldasIB4',
    appId: '1:908785933672:web:44038909450cce423d8add',
    messagingSenderId: '908785933672',
    projectId: 'rewardshub-9ba8b',
    authDomain: 'rewardshub-9ba8b.firebaseapp.com',
    storageBucket: 'rewardshub-9ba8b.firebasestorage.app',
    measurementId: 'G-BHLR5EYHP3',
  );
}
